### ISSUE TITLE
Agent chat session ended abruptly if agent reloads the page and streams takes more than 20 seconds to reconnect

### ISSUE THREAD

**Issue by rizwan5922** [amazon-connect/amazon-connect-chatjs#102]
Following is the scenario
An agent is handling a chat and he refreshes the page.
Sometimes amazon connect streams takes more than 20 seconds to re-establish the connection, (usually the authorize API response is delayed).
The agent disconnected from the chat session.

**Expected behavior:**
The agent chat session should remain intact for a longer period.
**Is there any configuration where this agent reconnect time can be configured to more than 20 seconds?**

**Comment by jagadeeshaby** [comment]
>Sometimes amazon connect streams takes more than 20 seconds to re-establish the connection

This does seem like problematic, is it possible for you to share more details on the same here?  or you could also reach out to AWS support where you could share details around instance, HAR file etc for us to dive deep further. 

> The agent chat session should remain intact for a longer period.

This isn't something we expose as an option via CCP/Streams today , I'll make sure to track this as a feature request, and update this when we know more

**Comment by spencerlepine** [comment]
Hi @rizwan5922,

Team has released update fix WebSocketManager heartbeat. Heartbeat will now be restored after losing connection for over 10s. Please install `amazon-connect-chatjs@^1.5.0` to apply this fix. ChatJS does not currently configuring the lost connection/heartbeat further.

If you have further issue with streams, please raise issue on [amazon-connect-streams](https://github.com/amazon-connect/) repository.

Resolving this issue for due to staleness. Please feel free to re-open or reach out if there are further questions.

Thanks,
Spencer
