### ISSUE TITLE
 Issue with setGlobalConfig and messageReceipts in Amazon Connect ChatJS

### ISSUE THREAD

**Issue by bradley3322** [amazon-connect/amazon-connect-chatjs#222]
**Description**:

We are developing a customer UI application utilizing Amazon Connect ChatJS. While implementing message receipts, we encountered an issue when using chatSession.setGlobalConfig to lower the throttle time.

**Steps to Reproduce:**

    Implement chatSession.setGlobalConfig with the features field declared as follows:

    react typescript

    features: {
        messageReceipts: {
            shouldSendMessageReceipts: true,
            throttleTime: 1000
        }
    }

    Returns the error: Ignoring messageReceipt: false.
    If the features field and its internal fields are not declared, the functionality works as expected with the default 5-second throttle time when using the .sendEvent function.

**Expected Behavior:**

    The throttle time should be reduced without encountering the error, and message receipts should be sent as configured.

**Observed Behavior:**

    The throttle time is reduced, but we receive an error message: Ignoring messageReceipt: false when using the .sendEvent function.

**Code Example:**

  React typescript 
  
  chatSession.setGlobalConfig({
      features: {
          messageReceipts: {
              shouldSendMessageReceipts: true,
              throttleTime: 1000
          }
      }
  });

**Additional Context:**
   Amazon Connect ChatJS version: [2.2.4]
We have also tested with the shouldSendMessageReceipts field removed to allow it to be set to the default but this results in the same behaviour

**Comment by bradley3322** [comment]
Hi,

Thank you for your attention to this matter. While I am unable to provide a minimum sample app due to certain constraints, I can share the implementation details of our current solution.

### 1. Global Configuration

We are using the connect.ChatSession.setGlobalConfig method to configure our chat session. This includes enabling message receipts and setting a throttle time. Below is the code snippet:

```
connect.ChatSession.setGlobalConfig({
  features: {
    messageReceipts: {
      shouldSendMessageReceipts: true, // DEFAULT: true, set to false to disable Read/Delivered receipts
      throttleTime: 500
    }
  }
});
```

### 2. Creating the Chat Session

After setting the global configuration, we create the chat session using ChatSession.create before starting the connection. Here is the implementation:



```
const customerChatSession = connect.ChatSession.create({
  chatDetails: cnn.getMediaInfo(),
  options: { 
    region: 'us-east-1',
  },
  type: connect.ChatSession.SessionTypes.AGENT,
  websocketManager: connect.core.getWebSocketManager()
});


const {connectSuccess} = await startConnection(agentChatSession, contact?.contactId);
```

### 3. Sending Events

The sendEvent method is called only after the agent sends a message. By this point, the connection and session have been established and the configuration is in place. The code for sending events is as follows:

```
const response = await chatSession.sendEvent({
  contentType: "application/vnd.amazonaws.connect.event.delivered",
  content: JSON.stringify({messageId: data.Id}) // messageId from the send message response
});
```

### 4. Console Log

Please refer to the attached screenshot for the console log showing each event step by step.
![Screenshot 2024-07-06 141701](https://github.com/amazon-connect/amazon-connect-chatjs/assets/89600482/0d8ccf60-f294-402b-8d60-1b83989f73a0)

If you need further details or have additional questions, please let me know.

Thank you

**Comment by mhiaror** [comment]
Hi @bradley3322 

From logs it seems like the issue is happening in Agent UI using ConnectStreams SDK with ChatJS SDK. 

I am confused, because you mentioned you are building `customer UI application using ChatJS` ?

Also, I see multiple instances of log `INFO ["new features added, initialValue:  , newValue: MESSAGE_RECEIPTS_ENABLED",true] ` , seems like there are multiple instances of the SDK in the same browser. Ideally, we should see this message only once . 

QQ. Why do you have multiple SDKs initialized ? I see logs from minimized version of Streams SDK, non-minified version of Streams SDK, ChatsessionHandler logs ?

Pls note than `GlobalConfig` is a singleton in your browser https://github.com/amazon-connect/amazon-connect-chatjs/blob/9b0147fd696a8c40952dcc8e38a1e613da406227/src/globalConfig.js#L4 but from logs it does not seem like a singleton, If you can not share sample application. Best path forward is if you can add a debugger here and ensure its not initialized multiple times and acts as a singleton.

**Comment by bradley3322** [comment]
I apologize for any confusion. In my previous message, I referred to it as a ‘customer UI,’ but I meant "representative UI"

I will respond to the questions asked after conducting a review. Thank you for your understanding and patience

**Comment by vkennedy** [comment]
Hi @mhiaror,

I have also seen this issue, and added some logging to see what is going on. It seems there is a mismatch of what is being advised to pass in to setGlobalConfig and how it is then used to actually update the config.

I moved the LogManager up so that I could add logging to the first time the call to update the config is done:
![image](https://github.com/user-attachments/assets/c42dd625-e429-4dfa-b5e1-689d5b5384f1)

I then also added logging within the globalConfig constructor and update function:
![image](https://github.com/user-attachments/assets/5944ec49-d50b-4cbe-a942-4d1cd2f0ed72)

The logs then show that the shouldSendMessageReceipts value is passed in, and we can see that the MESSAGE_RECEIPTS_ENABLED value is set in the features  (as per the constructor), but during the update it is removed.
![image](https://github.com/user-attachments/assets/4af7298e-cfd4-4bab-810b-2d69eed7c7ac)

This seems to be because as per the README instructions for connect.ChatSession.setGlobalConfig(), we are passing in a 'features' object with various keys, yet the update function is expecting an array of feature values. Since the features object passed in is not an array, then it just gets initialised to an empty array in the update function.

Possible changes needed:
- In setGlobalConfig, grab current GlobalConfig 'features' attribute, then parse in provided config to convert to array of valid features to then be used instead so that the update can go ahead properly, OR;
- After the call to update, grab relevant features provided in the config passed in and explicitly set each one individually.

**Comment by rupeshpatil9** [comment]
Hi @mhiaror 

We are also building a customer-facing chat interface using Amazon Connect ChatJS and encountering the same issue related to message receipts. Specifically, when we configure chatSession.setGlobalConfig with messageReceipts, we see the error Ignoring messageReceipt: false.

code :

`        connect.ChatSession.setGlobalConfig({
          loggerConfig: {

            customizedLogger: {
              debug: (...msg) => console.debug(...msg),
              info: (...msg) => console.info(...msg),
              warn: (...msg) => console.warn(...msg),
              error: (...msg) => console.error(...msg)
            },
            level: connect.LogLevel.ERROR,

            useDefaultLogger: true
          },
          region: "us-east-1",

          features: {
            messageReceipts: {
              shouldSendMessageReceipts: true,
              throttleTime: 1000
            }
          }
        });`

When we set shouldSendMessageReceipts: true, the error Ignoring messageReceipt: false appears.

If we do not include the messageReceipts field, no such error occurs, but the functionality reverts to the default throttle time (**5 seconds**).

Observed Behaviour:

With the configuration above, we consistently see the error Ignoring messageReceipt: false.
If we omit the messageReceipts field, the issue does not occur, but we are unable to modify the throttle time as needed.

Logs:
![image (10)](https://github.com/user-attachments/assets/256755c2-713b-4d14-9b9c-d537f45f35b8)
![image (11)](https://github.com/user-attachments/assets/a672784e-35d6-400d-9d47-5bf35fbb3366)

**Comment by mhiaror** [comment]
Created PR for the fix https://github.com/amazon-connect/amazon-connect-chatjs/pull/236
