### ISSUE TITLE
Sync onTyping Event

### ISSUE THREAD

**Issue by griffisc306** [amazon-connect/amazon-connect-chatjs#26]
Hello, 
Does anybody know the best way to display a bubble to customer for agent on typing and have it stop of the agent stops typing? So far we are able to display it but it doesn't go away until a message is sent

**Comment by mschersten** [comment]
I believe that Connect does send another typing event after the agent has stopped typing for some amount of time (10-20 seconds?).  So if your customer chat has a method like toggleTypingBubble() then that should get another event to trigger that.

My issue was that Connect doesn't send another typing event if the agent sends the message before that interval, so we would get a typing event, then a message, and the typing bubble would still show.  Then when they started typing again, it would turn off instead of on.  So we needed a method like stopTypingBubble() to call when a message came in, before displaying the message.

The combination of a toggle and stop method worked for us, without needing a start method as well.

**Comment by mhipszki** [comment]
@griffisc306 there's only a single typing event coming through from the agent. You need to set a timeout yourself on your custom UI to hide the typing indicator you're showing, also hide it when a message comes in from the agent. The implementation is up to you, but this is the essential part. Hope this helps! :)

**Comment by griffisc306** [comment]
Yep we were able to implement a timer.
