### ISSUE TITLE
How to accept and reject chat session manually.

### ISSUE THREAD

**Issue by dineshni** [amazon-connect/amazon-connect-chatjs#30]

**Comment by dineshni** [comment]
Is there any way manage the chat Accepting and Rejection function

**Comment by tscheuneman** [comment]
Hi @dineshni, sorry about the late response.  I assume you're talking about this from the agent side?  In that case, you might want to look at https://github.com/amazon-connect/amazon-connect-streams

**Comment by spencerlepine** [comment]
Hi @dineshni, any updates on this issue? Were you able to implement this functionality?

Thanks,
Spencer

**Comment by spencerlepine** [comment]
Hi @dineshni ,

You can follow steps in the [README#connectchatsessioncreate](https://github.com/amazon-connect/amazon-connect-chatjs#connectchatsessioncreate) to create Agent session. From there you can use `contact.accept()` or `contact.reject()`, which is listed in [Connect Streams Documentation](https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md)

Closing this issue due to long staleness (+ likely no visibility due to zero user activity on GitHub in 3 years)

Please feel free to re-open or reach out if there are further question. If there is `amazon-connect-streams` specific issue as well, feel free to raise is issue [here](https://github.com/amazon-connect/amazon-connect-streams)

Thanks,
Spencer
