### ISSUE TITLE
Support for React Native applications

### ISSUE THREAD

**Issue by jospas** [amazon-connect/amazon-connect-chatjs#42]
I building out a React Native chat demo using Expo I found that everything worked right up until receiving messages back down the web-socket when running on Android.

The exact same code worked fine using webpack or via remote debugging (actually runs inside Chrome) so I assume there is a window dependency or perhaps other web-socket browser dependency breaking the use of this library in React Native projects

I dropped back to using raw web-sockets and the participant API with no problems, it just would have been nice to use chat-js

Josh

**Comment by S1rFrancis** [comment]
I am also experiencing the same issue, this library does not work on an Android react native app unless the dev tools are running.

**Comment by cbettridgehs** [comment]
Ive also hit this issue in my react native app on Android. It appears the connection is being setup but onMessage is not being triggered.

**Comment by johnmryan** [comment]
Thanks all, will look into this. @jospas , do you know if you get any error logs running it on mobile?

**Comment by jospas** [comment]
This one is a true Heisenbug, if you enable debugging to get logs it actually runs the component in the browser locally when using Expo then the issue goes away as the web socket support in the browser is used.

**Comment by klozano** [comment]
Any news on this? I'm facing with the same issue related to the socket

**Comment by ocho-cesar** [comment]
I'm not being able to use it on iOS either. But by using Expo web, it works.

The only error I see in both environments is

```
Error while converting argument to string, constructor {
  "data": Object {
    "InitialContactId": "XXX",
    "NextToken": "",
    "Transcript": Array [],
  },
  "error": null,
  "httpResponse": constructor {
    "_abortCallback": [Function o],
    "body": Object {
      "data": Array [
          …
```

**Comment by ocho-cesar** [comment]
In order to make this library compatible with React Native Amazon Connect team would need to update https://github.com/amazon-connect/amazon-connect-streams/blob/master/src/lib/amazon-connect-websocket-manager.js I didn't found any source code for this. But this interface is responsible of managing WS integrations.

**Comment by spencerlepine** [comment]
Hello all,

Reaching out with update for ChatJS support in React Native. The `v1.5.0` release included updates to `WebSocketManager` to unblock this issue.

Install `amazon-connect-chatjs@^1.5.0` and refer the [`ReactNativeSupport.md`](https://github.com/amazon-connect/amazon-connect-chatjs/blob/master/.github/docs/ReactNativeSupport.md) documentation.

## How to use:

Additional configuration can now be passed to `setGlobalConfig`, which is passed down to `WebSocketManager`:

```js
const customNetworkStatusUtil = () => {
  if (navigator && navigator.hasOwnProperty("onLine")) {
    return navigator.onLine;
  }

  return true;
}

connect.ChatSession.setGlobalConfig({
  loggerConfig: { /* ... */ },
  // ...
  webSocketManagerConfig: {
    isNetworkOnline: customNetworkStatusUtil,
  }
});
```

## Example Application
For reference, team has also released a React Native + ChatJS [Expo demo application](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/connectReactNativeChat).

**Comment by jospas** [comment]
@spencerlepine this is a great addition thank you! I haven't tested as yet, can you describe how this fixes the issue of no websocket implementation being present in native (non-debug deployments) or is this still pending?

I can see the additional configuration really just tunes the websocket manager to detect lack of websocket support or connectivity:

https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/8efb93cf53fd339cde71b3830e07f86bd538edaf/connectReactNativeChat/src/components/ChatWrapper.js#L14

What was the work around if you got websockets running in native?

**Comment by spencerlepine** [comment]
@jospas The work around was providing a way to pass down the network status native to each device/environment, since WebSocketManager was using a browser-only method to check.

Here are more details about root cause:

`WebSocketManager` will initialize + establish connection, checking bool value of `navigator.onLine`. When Hermes of JavaScriptCore engine is used, `navigator.onLine` was `undefined`- and `WebSocketManager` would think the device wasn't connected. Debugging in ReactNative seems to be running V8 Javascript engine, which supported `window.navigator`.

> There is also a heartbeat every 250ms, but this logic wasn't reached previously. 

<img width="812" alt="Screenshot 2023-04-18 at 12 25 37 PM" src="https://user-images.githubusercontent.com/60903378/232884047-0df5714c-0076-4e14-b357-7a3b7b3aeeb2.png">

First, to unblock non-browser environment, the function needed to ignore undefined `navigator.onLine`:

```js
const customNetworkStatusUtil = () => {
  if (navigator && navigator.hasOwnProperty("onLine")) {
    return navigator.onLine;
  }

  return true;
}

connect.ChatSession.setGlobalConfig({
  webSocketManagerConfig: {
    isNetworkOnline: customNetworkStatusUtil,
  }
});
```

WebSocketManager still should have know the true device network status - not just the `true` override. 

To achieve this, there are ReactNative network status checks that can be done, native to the device [[ref]](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/blob/8efb93cf53fd339cde71b3830e07f86bd538edaf/connectReactNativeChat/src/components/ChatWrapper.js#L38):

```js
import ChatSession from "./ChatSession";
import NetInfo from "@react-native-community/netinfo";
import "amazon-connect-chatjs"; // ^1.5.0 - imports global "connect" object 

let isOnline = true;

/** 
 * By default, `isNetworkOnline` will be invoked every 250ms
 * Should only current status, and not make `NetInfo.fetch()` call
 * 
 * @return {boolean} returns true if currently connected to network
*/
const customNetworkStatusUtil = () => isOnline;

const ReactNativeChatComponent = (props) => {

  /** 
   * Network event listener native to device
   * Will update `isOnline` value asynchronously whenever network calls are made
  */
  const unsubscribeNetworkEventListener = NetInfo.addEventListener(state => {
    isOnline = state.isConnected;
  });

  useEffect(() => {
    return unsubscribeNetworkEventListener();
  }, []);

  const initializeChatJS = () => {
    // To configure WebSocketManager, setGlobalConfig must be invoked
    connect.ChatSession.setGlobalConfig({
      // ...
      webSocketManagerConfig: {
        isNetworkOnline: customNetworkStatusUtil,
      }
    });
  }

  // ...
}
```
