### ISSUE TITLE
Zombie Contacts— Stopping chat contact on browser close

### ISSUE THREAD

**Issue by jheising** [amazon-connect/amazon-connect-chatjs#68]
Our agents get a lot of sessions where the user is no longer there when they answer a contact. This occurs when a user closes their browser before the agent picks up. Their contact session remains in the queue, even if they aren't physically there anymore.

Is there any way to automatically end a chat session if/when the user closes their browser window? We've tried hooking into browser unload events and calling the stopContact API, but this doesn't always work.

Is there any sort of heartbeat that exists on the chat websocket stream that can automatically close a chat after it goes silent?

**Comment by swiszm-amazon** [comment]
Hi, can you provide more information on what things you've already tried -- why browser unload events were not working for you?

Another option may be to configure your contact flow to periodically ask the customer to respond while in queue. You can accomplish this using the branches available, Timeout and Customer return, on a wait block. See https://docs.aws.amazon.com/connect/latest/adminguide/wait.html

**Comment by daleking** [comment]
We have this issue too, which needlessly ties up agents when we could otherwise give them feedback that the contact may no longer be there.

Browser unload events are not reliable, not guaranteed and unusable on mobile.  They trigger sometimes on some browsers in some cases but this goes a long way from resolving it.

Wait blocks are only relevant after the agent interaction has ended, so reconfiguring the contact flow does cannot solve the issue.

Since there is already an out-of-band mechanism for typing indicator (dots) a similar mechanism that sends an out-of-band heartbeat from the CCP to the chat client could help here.  The heartbeat would require an ack and a lack of heartbeat ack could be used to present the agent with a message such as "The client is no longer responding to the chat".  This would give the agent the opourtunity to end the contact and be available for other work.  No configuration needed just sensible default behaviour such as notifying after e.g. 2 missed heartbeats, 60 seconds apart.  For backwards compatibility missing the first heartbeat would disable the feature for older clients altogether.

This is also raised by someone else here: https://github.com/amazon-connect/amazon-connect-chat-interface/issues/40 with good suggestions around sendBeacon as an alternative.

**Comment by spencerlepine** [comment]
Hi @jheising and @daleking,

As mentioned above, browser unload events are not reliable.

Amazon Connect Chat has since released feature to support idle participant, which is best solution.

Please refer to documentation for more information:
- https://docs.aws.amazon.com/connect/latest/adminguide/setup-chat-timeouts.html
- https://github.com/amazon-connect/amazon-connect-chatjs#chatsessiononparticipantidle


#### Other links

- Launch Announcement: https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-connect-idle-chat-participant-events-auto-close-capability/
- Video: https://www.youtube.com/watch?v=sGbYTPH7kCk&ab_channel=AmazonWebServices
