### ISSUE TITLE
How to see whether chat attachments are enabled

### ISSUE THREAD

**Issue by adamkss** [amazon-connect/amazon-connect-chatjs#92]
Hey!

How may I check whether the chat attachments functionality is enabled or not in the connect instance?

I am building a custom CCP and I need to conditionally show the attachment icon button.

Thanks!

**Comment by swiszm-amazon** [comment]
This flag is exposed under `contact` objects in amazon-connect-streams. Sample code:
```
connect.contact((contact) => {
    contact.onConnected((c) => {
        const attachmentsEnabled = c.getContactFeatures().attachmentsEnabled;
        // trigger UI rendering update based on flag
    });
});
```

Since this is regarding custom CCP and data is not in ChatJS, further questions can be asked in https://github.com/amazon-connect/amazon-connect-streams . I have also reached out to owners of that package to request updating Streams documentation with how to use `getContactFeatures()`

**Comment by adamkss** [comment]
@swiszm-amazon thanks a lot!
